### ISSUE TITLE
Misleading GitHub Repository

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [DonHulieo/don-shootingrange#1]
The point of GitHub is that you upload your code free of charge and it's open source; what's the point of this? I see everyone praising it, yet you have to go to to your tebex.

I could understand advertising it on the FiveM forums but this seems pointless as hell.

**Comment by DonHulieo** [comment]
The entire point is providing the Configs, Images and README's where need be, and so that customers can be updated as soon as resources are updated. It's not an uncommon practice and is sure a hell of a lot better than screenshotting the config in advertisements.

**Comment by DonHulieo** [comment]
I also only sell 4 of the 10 scripts I have on my GitHub (and that's released scripts), I'd assume in the long run I'm providing a net benefit to the community, not otherwise.
